seed: 0
deterministic: false

checkpoint_config:
  interval: 1
  max_keep_ckpts: 1

log_config:
  interval: 50
  hooks:
    -
      type: TextLoggerHook
    -
      type: TensorboardLoggerHook

load_from: null
resume_from: null

cudnn_benchmark: false
fp16:
  # null
  loss_scale: 
    growth_interval: 2000
# lidar-only로 학습할 때, fp16: null fp16켜면 nan 뜸.
max_epochs: 20
runner:
  type: CustomEpochBasedRunner
  max_epochs: ${max_epochs}
